// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nadiano.Web.Infrastructure.Persistence;

#nullable disable

namespace Nadiano.Web.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NadianoDbContext))]
    partial class NadianoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Nadiano.Core.Practice.PracticeAttemptRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("NextActionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ResultSchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("PracticeAttempts", (string)null);
                });

            modelBuilder.Entity("Nadiano.Core.Practice.PracticeSessionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LessonId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("PracticeSessions", (string)null);
                });

            modelBuilder.Entity("Nadiano.Core.Profiles.LearnerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LearnerProfiles", (string)null);
                });

            modelBuilder.Entity("Nadiano.Core.Profiles.ProfilePreferences", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("NoteNameSystem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredMidiDeviceId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredMidiDeviceName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionLengthMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProfileId");

                    b.ToTable("ProfilePreferences", (string)null);
                });

            modelBuilder.Entity("Nadiano.Core.Progress.CourseEnrollment", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CourseId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("EnrolledAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("ProfileId", "CourseId");

                    b.ToTable("CourseEnrollments", (string)null);
                });

            modelBuilder.Entity("Nadiano.Core.Progress.LessonProgressRecord", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LessonId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ProfileId", "LessonId");

                    b.HasIndex("ProfileId", "CourseId");

                    b.ToTable("LessonProgress", (string)null);
                });

            modelBuilder.Entity("Nadiano.Core.Progress.SkillEvidenceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("LessonId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SelfReportedSuccess")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkillId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "LessonId");

                    b.ToTable("SkillEvidence", (string)null);
                });

            modelBuilder.Entity("Nadiano.Core.Practice.PracticeAttemptRecord", b =>
                {
                    b.HasOne("Nadiano.Core.Practice.PracticeSessionRecord", null)
                        .WithOne("Attempt")
                        .HasForeignKey("Nadiano.Core.Practice.PracticeAttemptRecord", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nadiano.Core.Practice.PracticeSessionRecord", b =>
                {
                    b.HasOne("Nadiano.Core.Profiles.LearnerProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nadiano.Core.Profiles.ProfilePreferences", b =>
                {
                    b.HasOne("Nadiano.Core.Profiles.LearnerProfile", null)
                        .WithOne()
                        .HasForeignKey("Nadiano.Core.Profiles.ProfilePreferences", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nadiano.Core.Progress.CourseEnrollment", b =>
                {
                    b.HasOne("Nadiano.Core.Profiles.LearnerProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nadiano.Core.Progress.LessonProgressRecord", b =>
                {
                    b.HasOne("Nadiano.Core.Profiles.LearnerProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nadiano.Core.Progress.SkillEvidenceRecord", b =>
                {
                    b.HasOne("Nadiano.Core.Profiles.LearnerProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nadiano.Core.Practice.PracticeSessionRecord", b =>
                {
                    b.Navigation("Attempt");
                });
#pragma warning restore 612, 618
        }
    }
}
